[package]
name = "cusco"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
cusco-executor = { path = "../executor" }
cusco-model-registry = { path = "../model-registry" }
cusco-server = { path = "../server" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
